{{- if not .Values.instana.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "instana.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  api-token: {{ .Values.instana.apiToken | b64enc | quote }}
{{- end }}
